### ISSUE TITLE
UI slightly broken on MacOS

### ISSUE THREAD

**Issue by Andreya-Autumn** [eventual-recluse/LiveCut#1]
Hello! And thanks for the work on this. Happy report this builds (with lots of warnings) on Mac, and the DSP seems to work fine. 

UI could use some help though. Shows up like this:

<img width="996" alt="Screenshot 2023-05-27 at 20 02 08" src="https://github.com/eventual-recluse/LiveCut/assets/105538426/ebd26960-ded3-44e3-883d-67f6f47623c2">

In case it helps: Host is reaper, platform is MacOS 11.6.5, all plugin formats do it. 

Thanks again for doing this. :)

**Comment by eventual-recluse** [comment]
I'll see what I can do. Is there any plugin window scaling happening there (for high resolution screens)?

PS Thanks for the feedback! Glad to know it builds on macOS.

**Comment by eventual-recluse** [comment]
Updated the GUI to account for scaling.

It should scale up correctly now.

**Comment by Andreya-Autumn** [comment]
Works perfectly now as far as I can tell. Good work. I'll let you know if I find anything else. Thanks again. :)

**Comment by eventual-recluse** [comment]
OK. Thanks!
