### ISSUE TITLE
Fade param scaling

### ISSUE THREAD

**Issue by Andreya-Autumn** [eventual-recluse/LiveCut#2]
Hello again. Here's a small UI nitpick: The original UI had a log scale on the fade param, such that 5ms was right in the middle. That was great, 5ms is right around the most useful range where annoying clicks dissappear but transients don't suffer too much. This new UI (which looks great here now that it scales correctly!) doesn't do that. Any chance that can be addressed? 

Thanks again. Enjoying playing with this. :)

**Comment by eventual-recluse** [comment]
The UI fade param is now logarithmic, but I'll need to investigate skewing it so 5 ms is right in the middle. (1 ms is currently the middle value.)

Glad to hear you're enjoying it!

**Comment by Andreya-Autumn** [comment]
Nice. Works great here. Honestly, maybe don't worry about making it 5ms exactly. 1ms mostly sounds fine for the treble-rich material that we mostly use this for. And with this log scaling it feels easy to dial in slower times when needed. So I think it's fine as it is now. 👍🏻

**Comment by eventual-recluse** [comment]
OK. I had a look but can't see an easy way to set the mid point with Dear ImGui, so I'll leave it as it is.
